FROM php:5.6-apache
RUN a2enmod rewrite
RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng12-dev \
        libxml2-dev \
        libexpat1-dev \
        zlib1g-dev \
        git-core \
        sendmail \
    && docker-php-ext-install -j$(nproc) iconv mcrypt mbstring zip \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) soap gd mysql mysqli pdo_mysql
RUN ln -sf /dev/stderr /var/log/apache2/error.log \
    && ln -sf /dev/stderr /var/log/apache2/php-error.log \
    && ln -sf /dev/stderr /var/log/apache2/devsubscriptions.thefoundry.co.uk_error.log \
    && ln -sf /dev/stderr /var/log/apache2/devlicenceapi.thefoundry.co.uk_error.log
RUN ln -sf /dev/stdout /var/log/apache2/access.log \
    && ln -sf /dev/stdout /var/log/apache2/devsubscriptions.thefoundry.co.uk_access.log \
	&& ln -sf /dev/stdout /var/log/apache2/devlicenceapi.thefoundry.co.uk_access.log
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php -r "if (hash_file('SHA384', 'composer-setup.php') === '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
    && php composer-setup.php \
    && php -r "unlink('composer-setup.php');"
RUN usermod -u 1000 www-data