FROM php:5.6-apache
RUN a2enmod rewrite
RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng12-dev \
        libxml2-dev \
    && docker-php-ext-install -j$(nproc) iconv mcrypt mbstring \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) soap gd mysql mysqli pdo_mysql \
	&& ln -sf /dev/stderr /var/log/apache2/php-error.log
COPY ../config/subs/sites-available/ /etc/apache2/sites-available/


RUN usermod -u 1000 www-data