FROM php:5.4-apache
# COPY config/php.ini /usr/local/etc/php
RUN a2enmod rewrite
RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng12-dev \
    && docker-php-ext-install iconv mcrypt mbstring \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install soap gd mysql mysqli pdo_mysql \
	&& ln -sf /dev/stderr /var/log/apache2/php-error.log
RUN usermod -u 1000 www-data
	# && chown -R www-data:www-data /var/www/html/files/tmp